"""create new table

Revision ID: 8ec754a4f5b9
Revises: 
Create Date: 2022-05-10 20:16:32.916296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ec754a4f5b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    op.drop_index('email', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index('descricao', table_name='categorias')
    op.drop_table('categorias')
    op.drop_index('cnpj', table_name='ongs')
    op.drop_table('ongs')
    op.drop_table('estoques')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoques',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('saldo', mysql.FLOAT(), nullable=False),
    sa.Column('meio', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name='estoques_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ongs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('razao_social', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('cnpj', mysql.VARCHAR(length=18), nullable=False),
    sa.Column('endereco', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('responsavel', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('site', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('token', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('cnpj', 'ongs', ['cnpj'], unique=False)
    op.create_table('categorias',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('descricao', 'categorias', ['descricao'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=86), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=84), nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('token', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'usuarios', ['email'], unique=False)
    op.create_table('produtos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('unidade_medida', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('quantidade_minima', mysql.FLOAT(), nullable=False),
    sa.Column('quantidade_maxima', mysql.FLOAT(), nullable=False),
    sa.Column('quantidade_ideal', mysql.FLOAT(), nullable=False),
    sa.Column('categoria_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name='produtos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
